### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by capedra** [SensorsIot/Pre-Compiler-Directives#1]
Professor, Congratulations for your library! Just as an improvement, I wonder if there is a way to pass flash-memory based strings to Serial.print() just like when we wrap them with F() somehow. I always use print this way because I remember the days when we had to save some memory on ESP8266's heap. Also, it would be even better if the library allowed us to use printf function passing some argument(s). Thanks a lot!

**Comment by SensorsIot** [comment]
I have no plans for updating this "library" for the moment.
